# https://glebbahmutov.com/blog/trying-github-actions/
name: update-branch
on:
  push:
  schedule:
    - cron: '0 3 * * *'
  # or update the branch main manually
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout 🛎
      # https://github.com/actions/checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update Git branch main
      run: |
        git config user.name "Update branch"
        git config user.email github-actions@github.com
        git checkout main
        git merge main --no-edit -m "Merged main branch on $(date +%F)"
    - name: Push the updated branch main
      run: |
        git push origin main