name: Update Branch

on:
  push:
  workflow_dispatch:

jobs:
  updateBranch:
    name: Update main branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/main'
      with:
        branch: main
        force: 1 # To push-force to the branch
        githubToken: ${{ secrets.PAT_TOKEN }}